### ISSUE TITLE
How to use the /data/name.csv file?

### ISSUE THREAD

**Issue by bruvv** [laurensvm/mp-automator#2]
Can you write small documentation with examples on how the file should look like?
@laurensvm ?

**Comment by bruvv** [comment]
bump

**Comment by bruvv** [comment]
bump

**Comment by bruvv** [comment]
please?

**Comment by bruvv** [comment]
halloooo

**Comment by laurensvm** [comment]
Hi bruvv, 

I forgot to reply to your issue. Honestly, this project should be redone, I just made this because I had a few long running ads. See attached an example of a .txt file containing the information. Place this file together with pictures in a file and the program will loop over it.

Hope this helps you.

[product.txt](https://github.com/laurensvm/mp-automator/files/3340466/product.txt)

**Comment by bruvv** [comment]
Laurens, held! haha Thanks :) 
wat bedoel je met plaatst de .txt + fotos in een bestand? Of moet dat folder zijn :) ? ben wel benieuwd omdat je programma een CSV leest als ik het goed begrijp?

**Comment by laurensvm** [comment]
Ik bedoel een bestand uiteraard. Hij doet ook csv, zie voorbeeld hieronder. 
[product.csv.zip](https://github.com/laurensvm/mp-automator/files/3341046/product.csv.zip)

**Comment by bruvv** [comment]
haha mooi thanks! Heb hem inmiddels helemaal werkend en geupdate naar hoe ik het prettig vind :) Thanks voor het voor werk en de hulp!
